console.log(Math.random() * 25)

//Multiplication with Random numbers only define it's heigher range. It means the heigher range of the above code goes upto 25.

console.log(Math.random() * 25 + 5)

//Multiplication set ->  Higher range of the random number
//Addition set -> Range (Low to High)

/**
 * let say the first generated number is :- 0.215...
 * Now, because of adding 5 into the random number it become 5.215....
 * 
 * And let say the heigher number that is generated by random number is 25.215
 * Now, because of adding 5 into the random number it would become 30.215....
 * 
 * So, the range of the random number is :- from 5(or 5+) to 30(less than 30)
 */

//Let's get simple integer value

//Math.floar(random generate) -> Get lowest value
//Math.round(random generate) -> Get round-up value
//Math.ceil(random generate)  -> Get highest value

console.log("Floar", Math.floor(Math.random() * 25 + 5))    //Range -> 5 to 29
console.log("Round", Math.round(Math.random() * 25 + 5))    //Range -> 5 to 30
console.log("Ceil", Math.ceil(Math.random() * 25 + 5))      //Range -> 6 to 30